package co.za.quickbuyticketcomponent.modals;
// Generated Dec 28, 2017 1:58:40 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.*;

/**
 * AccountType generated by hbm2java
 */
@Entity
@Table(name="AccountType"
)
public class AccountType implements java.io.Serializable {


    private int accountTypeId;
    private String accountTypeDesc;

    public AccountType() {
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "AccountTypeId", unique = true, nullable = false)
    public int getAccountTypeId() {
        return accountTypeId;
    }

    public void setAccountTypeId(int accountTypeId) {
        this.accountTypeId = accountTypeId;
    }

    @Column(name = "AccountTypeDesc", nullable = false, length = 50)
    public String getAccountTypeDesc() {
        return accountTypeDesc;
    }

    public void setAccountTypeDesc(String accountTypeDesc) {
        this.accountTypeDesc = accountTypeDesc;
    }

    @Override
    public String toString() {
        return "AccountType{" +
                "accountTypeId=" + accountTypeId +
                ", accountTypeDesc='" + accountTypeDesc + '\'' +
                '}';
    }
}


