package co.za.quickbuyticketcomponent.modals;
// Generated Dec 28, 2017 1:58:40 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.*;

/**
 * AccountType generated by hbm2java
 */
@Entity
@Table(name="account_type"
)
public class AccountType implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "account_type_id")
    private int accountTypeId;

    @Column(name = "account_type_desc")
    private String accountTypeDesc;

    public AccountType() {
    }


    public int getAccountTypeId() {
        return accountTypeId;
    }

    public void setAccountTypeId(int accountTypeId) {
        this.accountTypeId = accountTypeId;
    }

    public String getAccountTypeDesc() {
        return accountTypeDesc;
    }

    public void setAccountTypeDesc(String accountTypeDesc) {
        this.accountTypeDesc = accountTypeDesc;
    }

}


